apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: mini-shoping
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 32003
  type: NodePort
