apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: mini-shoping
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      type: clusterIP
